---

- hosts: all # we want to run on all the hosts
  become: true # ansible 
  tasks:
  
  - name: update repo index
    dnf: 
      update_cache: yes
    when: ansible_distribution == "RedHat"
      

  - name: Installing the httpd package
    dnf: 
      name: httpd 
      state: latest #if we replace "latest" with "absent", then the package will be uninstalled
    when: ansible_distribution == "RedHat"

  - name: Installing PHP Support to httpd
    dnf: 
      name: php
      state: latest #replace "latest" with "absent to reverse the changes"
    when: ansible_distribution == "RedHat"
