---

- hosts: all
  become: true
  tasks:

  - name: install Apache/Httpd pachages
    apt: 
      name:
        - apache2
        - libapache-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

